#!/bin/bash

# $Editor: vpastukhov $
# $Id: stop,v 1.3 2004/02/08 14:01:37 vpastukhov Exp $
# $Revision: 1.3 $

reldir=`dirname "$0"`
reldir=`cd "$reldir" ; pwd`

INSTANCE_HOME="$reldir"

PID=`cat "$INSTANCE_HOME/var/Z2.pid" 2> /dev/null`
if [ "$PID" ]; then
    kill $PID 2> /dev/null
fi

if [ -x "$reldir/stop_zeo" ]; then
    "$reldir/stop_zeo"
fi
