## Script (Python) "directory_entry_handler"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=REQUEST, code=None, title=None, ids=None
##title=
##
# $Editor: vpastukhov $
# $Id: directory_entry_handler.py,v 1.12 2006/08/15 08:33:57 oevsegneev Exp $
# $Revision: 1.12 $

from Products.CMFNauTools.SecureImports import SimpleError, refreshClientFrame

action_list  = 'directory_view'
action_entry = 'directory_entry_form'
action_error = action_list
params = {}
is_branch = 0

root = context.getDirectory()
node = None
message = None

try:
    if REQUEST.has_key('add_entry_form'):
        return context.directory_entry_form( context, REQUEST, add_element_type='entry' )

    elif REQUEST.has_key('add_branch_form'):
        return context.directory_entry_form( context, REQUEST, add_element_type='branch' )

    elif REQUEST.has_key('add_entry') or REQUEST.has_key('add_branch'):
        action_error = action_entry
        is_branch = REQUEST.has_key('add_branch')
        params['add_element_type'] = is_branch and 'branch' or 'entry'
        node = context

        if root.getCodeColumn().allowsInput():
            code = code.strip() or None
        else:
            code = None

        if is_branch:
            entry = node.addBranch( code )
        else:
            entry = node.addEntry( code )

        # remember code in case it was autogenerated
        code = entry.code()

        if root.getTitleColumn().allowsInput():
            entry.setTitle( title )

        attrs = {}
        for column in entry.listColumns():
            if column.allowsInput():
                name = 'attr/%s' % column.name()
                if REQUEST.has_key( name ):
                    attrs[ column.name() ] = REQUEST[ name ]

        entry.setEntryAttributes( **attrs )


    elif REQUEST.has_key('delete_entries'):
	#TODO check whether entries is branches
	is_branch = 1
        node = context

        if ids:
            node.deleteEntries( *ids )
            if len(ids) == 1:
                message = "Entry has been deleted."
            else:
                message = "Entries have been deleted."
        else:
            message = "Please select one or more entries first."

    elif REQUEST.has_key('save_entry'):
        action_error = action_entry
        entry = context
	is_branch = entry.isBranch()
        node = entry.getParent()

        if root.getCodeColumn().allowsInput():
            entry.setCode( code.strip() )

        if root.getTitleColumn().allowsInput():
            entry.setTitle( title )

        attrs = {}
        for column in entry.listColumns():
            if column.allowsInput():
                name = 'attr/%s' % column.name()
                if REQUEST.has_key( name ):
                    attrs[ column.name() ] = REQUEST[ name ]

        entry.setEntryAttributes( **attrs )

        message = "Attributes changed."

    elif REQUEST.has_key('cancel'):
        message = "Action cancelled."

    elif REQUEST.has_key('cut_entries'):
        node = context
        if REQUEST.has_key('ids'):
            try:
                context.cutObjects(REQUEST['ids'], REQUEST)
                message='Item(s) Cut'
            except:
                message='unauthorized'
        else:
            message='Please select one or more items to cut first'

    elif REQUEST.has_key('paste_entries'):
        node = context
        try:
            context.pasteObjects(REQUEST)
            message='Item(s) Pasted'
        except:
            message='unauthorized'


except SimpleError, error:
    error.abort()
    params['portal_status_message'] = error
    return getattr(context, action_error)( context, **script.values( **params ) )

if node is None:
    if context.implements('IDirectoryEntry'):
        node = context.getParent()
    if node is None:
        node = root

if is_branch:
    refreshClientFrame('directory')

return node.redirect( action=action_list, message=message, REQUEST=REQUEST )
