"""
Defines ErrorLogTool class - portal error logging and reporting tool.

$Editor: vpastukhov $
$Id: ErrorLogTool.py,v 1.27 2005/12/23 12:40:47 ikuleshov Exp $
"""
__version__ = '$Revision: 1.27 $'[11:-2]

from sys import exc_info
from time import strftime, localtime

import transaction, Zope2 as Zope
from AccessControl import ClassSecurityInfo
from AccessControl.SecurityManagement import getSecurityManager
from AccessControl.User import nobody as NobodyUser
from Acquisition import aq_inner, aq_parent, aq_get
from ZODB.Connection import ConflictError
from zLOG import LOG, ERROR

try:
    from ZODB.PersistentList import PersistentList
except ImportError:
    PersistentList = None

from Products.CMFCore import CMFCorePermissions
from Products.CMFCore.ActionProviderBase import ActionProviderBase
from Products.CMFCore.Expression import Expression
from Products.CMFCore.utils import UniqueObject, getToolByName, _checkPermission

try:
    from Products.SiteErrorLog.SiteErrorLog import SiteErrorLog
except ImportError:
    # XXX recall why SimpleItem is needed
    from OFS.SimpleItem import SimpleItem as SiteErrorLog

import Config
from Config import Permissions
from Exceptions import SimpleError, Unauthorized, formatErrorValue, formatException
from SimpleObjects import ToolBase
from Utils import InitializeClass


class ErrorLogTool( ToolBase, SiteErrorLog ):
    """
        Portal error logging tool.

        Basically this tool replicates behaviour of the 'error_log' object
        of Zope (which it is based on) with additional improvements over it,
        namely the ability to send report to the administrator or product
        support by e-mail, extended exception information and persistent log
        entries.

        Each error log entry is a dictionary containing exception
        and environment information. All entries are stored in the single
        persistent list, limited to Config.MaxErrorLogEntries in length.

        Only available under Zope >= 2.6.
    """
    _class_version = 1.3

    id = 'portal_errorlog'
    meta_type = 'NauSite Error Log Tool'

    security = ClassSecurityInfo()

    manage_options = SiteErrorLog.manage_options + \
                     ActionProviderBase.manage_options

    security.declareProtected( Permissions.UseErrorLogging, 'getProperties' )
    getProperties = SiteErrorLog.getProperties

    security.declareProtected( CMFCorePermissions.ManagePortal, 'setProperties' )
    setProperties = SiteErrorLog.setProperties

    keep_entries = Config.MaxErrorLogEntries
    _ignored_exceptions = ()

    def _initstate( self, mode ):
        #
        # Initialize attributes.
        #
        if not ToolBase._initstate( self, mode ):
            return 0

        if not ( hasattr( self, '_log' ) or PersistentList is None ):
            self._log = PersistentList()

        return 1

    security.declareProtected( Permissions.UseErrorLogging, 'raising' )
    def raising( self, info=Missing ):
        """
            Logs an exception.

            Called by exception handler (see Zope.zpublisher_exception_hook)
            if Python exception is generated by the request handler.

            Exception argument is made optional so that this method can
            be used from scripts to log the last exception (for debugging
            purposes).

            Appends collected exception and environment information to the
            error log.  Ignores unauthorized exceptions for anonymous requests.

            Arguments:

                'info' -- tuple with the exception information
                          (type, value, traceback); optional

            Result:

                Absolute URL of the corresponding error log entry page.
        """
        if info is Missing:
            info = exc_info()
            if not filter( None, info ):
                return None

        # abort transaction before SiteErrorLog.raising
        transaction.abort()
        etype, value, tb = info
        try:
            REQUEST = aq_get( self, 'REQUEST', None )

            if REQUEST is not None:
                # ignore anonymous requests
                if etype is Unauthorized and not REQUEST._auth:
                    return None
                # try to authenticate user in case of publishing errors
                pub_errors = [ 'Debug Error', 'NotFound', 'Forbidden' ]
                if REQUEST._auth and etype in pub_errors \
                        and getSecurityManager().getUser() is NobodyUser:
                    try: REQUEST.clone().traverse( self.physical_path() )
                    except: pass

            tb  = formatException( etype, value, tb )
            url = SiteErrorLog.raising( self, (etype, value, tb) )
        finally:
            tb = info = None
            del tb, info

        if url is None:
            return None # ignored exception

        log = self._getLog()
        entry = log[-1] # XXX race condition

        entry['time_str'] = strftime( '%Y-%m-%d %H:%M:%S', localtime( entry['time'] ) )

        try:    entry['value'] = str( formatErrorValue( etype, value ) )
        except: entry['value'] = '<unprintable %s object>' % str( type(value).__name__ )

        entry['req_text'] = ''
        if REQUEST is not None:
            try:    entry['req_text'] = REQUEST.text()
            except: pass

            try:    entry['username'] = getToolByName( self, 'portal_membership' ).\
                                        getMemberName( entry['userid'] )
            except: pass

            REQUEST.set( '_LastLogEntryId', entry['id'] )

        entry['version']      = Config.ProductEdition
        entry['zope_info']    = Config.ZopeInfo
        entry['zodb_info']    = Config.ZODBInfo
        entry['python_info']  = Config.PythonInfo
        entry['system_info']  = Config.SystemInfo

        active_addons = getToolByName( self, 'portal_addons' ).listActiveAddons()
        entry['active_addons'] = ','.join( active_addons )

        licensing = getToolByName( self, 'portal_licensing', None )
        if licensing is not None:
            entry['license_info']  = licensing.getLicenseUsage()
        else:
            entry['license_info']  = 'n/a'

        entry['comment'] = entry['comment_adm'] = ''

        # the transaction was aborted by the exception handler,
        # thus we can (almost) safely commit our log entry
        for i in range(3):
            try:
                # only commit log
                trans = transaction.get()
                if REQUEST is not None:
                    object = REQUEST.get( 'PUBLISHED', self )
                    Zope.zpublisher_transactions_manager.recordMetaData( object, REQUEST )
                else:
                    trans.note( self.physical_path() )
                trans.note( "logged exception" )
                trans.commit()
            except ConflictError:
                log.append( entry )
                continue
            except:
                LOG( 'ErrorLogTool.raising', ERROR,
                     "Cannot save error log entry [%s]:" % entry['id'], error=exc_info() )
            break

        return url

    security.declareProtected( CMFCorePermissions.AccessContentsInformation, 'getLogEntryById' )
    def getLogEntryById( self, id=None ):
        """
            Returns the specified log entry.

            Makes a copy to prevent changes. If log entry id is not specified,
            returns the last error entry for the current request.

            Arguments:

                'id' -- optional log entry id

            Result:

                The copy of the log entry (Python dictionary)
                or 'None' if not found.
        """
        return self._getLogEntry( id )

    security.declarePublic( 'getLastEntryId' )
    def getLastEntryId( self, REQUEST=None ):
        """
            Returns id of the most recent log entry for the request.

            Arguments:

                'REQUEST' -- specifies Zope request object; if not given
                             the method will try to acquire it from context

            Result:

                The id of the log entry or None if not found.
        """
        REQUEST = REQUEST or aq_get( self, 'REQUEST', None )
        return REQUEST and REQUEST.get( '_LastLogEntryId' )

    security.declarePublic( 'getLogEntryAsText' )
    def getLogEntryAsText( self, id, REQUEST=None ):
        """
            Returns log entry formatted as plain text.

            Arguments:

                'id' -- log entry id

                'REQUEST' -- optional Zope request object; if present,
                             the method will set text/plain content type
                             in the response

            Result:

                Multiline text string describing error.
        """
        if REQUEST is not None:
            charset  = REQUEST.get( 'LOCALIZER_CHARSET', '' )
            RESPONSE = REQUEST.RESPONSE
            RESPONSE.setHeader( 'content-type', 'text/plain; charset=%s' % charset )
        else:
            RESPONSE = None

        entry = self._getLogEntry( id, copy=False )
        if entry is None:
            if RESPONSE is None:
                return None

            msgtool = getToolByName( self, 'msg' )
            return msgtool( "Log entry [%(id)s] not found or expired." ) % { 'id':id }

        return _entryTextTemplate % entry

    def _getLog( self ):
        """
            Returns the log entry container for this object.

            Result:

                The persistent list object containing log entries.
        """
        try:
            return self._log
        except AttributeError:
            return SiteErrorLog._getLog( self )

    def _getLogEntry( self, id=None, copy=True ):
        """
            Returns the specified log entry or None.

            Used by public methods.  If 'id' is not specified,
            returns the last error entry for the current request.
            Checks whether the current user is allowed to view
            the entry (either its owner or has 'Log Site Errors'
            permission).

            Arguments:

                'id' -- optional log entry id

                'copy' -- boolean flag, true to make and return
                          a copy of the log entry to prevent changes
                          (default)

            Result:

                The log entry (Python dictionary) or 'None' if not found.
        """
        id = id or self.getLastEntryId()
        if not id:
            return None

        log = self._getLog()
        for entry in log:
            if entry['id'] == id:
                break
        else:
            return None

        # XXX should check context of the user
        user = getSecurityManager().getUser().getUserName()
        if user != entry['userid']:
            # ordinary users are allowed to view only their own entries
            if not _checkPermission( Permissions.UseErrorLogging, self ):
                raise Unauthorized( id, entry )

        return copy and entry.copy() or entry

    security.declarePublic( 'sendErrorReport' )
    def sendErrorReport( self, id, comment='', admin=None, support=None, email=None, REQUEST=None ):
        """
            Sends error report to the administrator and support service by e-mail.

            Error reports can be sent only by the user who faced
            the error, or by the administrator. User's comment gets added
            to the error log entry.

            Either portal administrator (by default) or product support
            service or both may be specified as the recipients of the report.
            Administrator's e-mail address is taken from the portal
            configuration, whereas support e-mail is specified as the
            Config.ErrorReportAddress value.

            For the administrator notification 'error_notify_admin' mail
            template is used, which includes only user's comment and basic
            exception information, along with link to the error entry page.

            Support service receives full error report.

            Arguments:

                'id' -- log entry id

                'comment' -- optional user's comment on the error

                'admin' -- optional flag indicating whether to notify
                           portal administrator

                'support' -- optional flag indicating whether to notify
                             product support service

                'email' -- optional e-mail address to send error
                           notification to

                'REQUEST' -- optional Zope request object

            Result:

                Redirect URL to the portal status page if the REQUEST
                is given.
        """
        try:
            entry = self._getLogEntry( id, copy=0 )
            if entry is None:
                raise SimpleError( "Log entry %(id)s not found or expired.", id=id )

            comment = comment.strip()
            if entry['comment']:
                entry['comment_adm'] = comment
            else:
                entry['comment']     = comment
                entry['comment_adm'] = '\n'.join( [ '> ' + line for line in comment.split('\n') ] )

            email = email and [email] or []

            if support and _checkPermission( Permissions.UseErrorLogging, self ):
                email.append( Config.ErrorReportAddress )

            if admin or not email:
                admin = getToolByName( self, 'portal_properties' ).\
                        getProperty( 'email_from_address' )

            if not ( admin or email ):
                raise SimpleError( "Administrative e-mail address is not set in the portal configuration." )

            mail  = getToolByName( self, 'MailHost' )
            count = 0

            if admin:
                count += mail.sendTemplate( 'error_notify_admin', \
                                            [ admin ], from_member=True, \
                                            id=id, comment=comment, entry=entry, \
                                            restricted=Trust, raise_exc=True )

            if email:
                # TODO: must have another mail template
                text = self.getLogEntryAsText( id )
                msg = mail.createMessage( 'text/plain' )
                msg['subject'] = 'Error report'
                msg.set_payload( comment + '\n' + text )
                count += mail.send( msg, email, from_member=1, raise_exc=1 )

            if not count:
                raise SimpleError( "Delivery of the error report failed." )

        except SimpleError, message:
            pass
        else:
            message = "Error report has been sent."

        if REQUEST is not None:
            return self.parent().redirect(
                        action   = 'status_page',
                        message  = message,
                        params   = { 'id':id },
                        REQUEST  = REQUEST,
                    )

    def _containment_onAdd( self, item, container ):
        # sets __error_log__ on the container
        SiteErrorLog.manage_afterAdd( self, item, container )

    def _containment_onDelete( self, item, container ):
        # unsets __error_log__ on the container
        SiteErrorLog.manage_beforeDelete( self, item, container )

InitializeClass( ErrorLogTool )


# template used by getLogEntryAsText

_entryTextTemplate = \
"""

SYSTEM INFORMATION

NauDoc Version:  %(version)s
Active Addons:   %(active_addons)s
Zope Version:    %(zope_info)s
ZODB Version:    %(zodb_info)s
Python Version:  %(python_info)s
System Platform: %(system_info)s

EXCEPTION INFORMATION

Error ID:        %(id)s
Time:            %(time_str)s
User Name:       %(userid)s (%(username)s)
Request URL:     %(url)s
Exception Type:  %(type)s
Exception Value: %(value)s

EXCEPTION TRACEBACK

%(tb_text)s

REQUEST

%(req_text)s
"""

def initialize( context ):
    # module initialization callback

    context.registerTool( ErrorLogTool )
