"""
Rendering object hierarchies as Trees
multiple tags per page possible.
Tags on serveral pages may share status.

$Editor: ypetrov $
$Id: JungleTag.py,v 1.69 2008/03/26 14:59:34 oevsegneev Exp $
"""
__version__ = '$Revision: 1.69 $'[11:-2]

from sets import Set
from types import StringType

from DocumentTemplate.DT_Util import *
from DocumentTemplate.sequence import SortEx

from Products.CMFCore.utils import getToolByName
from TreeDisplay.TreeTag import encode_seq, decode_seq
from zLOG import LOG, DEBUG, TRACE, INFO

from interfaces.IJungleTree import IBasicTree
from ResourceUid import getCatalogByType, ResourceUid
from Utils import addQueryString, joinpath, splitpath, pathdelim, getObjectImplements

_transmitted_args = ('sort_order', 'state_url', 'meta_types', 'implements', 'dynamic_item_id', 'urlparams')

class ContentTree( object ):
   
    __implements__ = IBasicTree

    def __init__(self, content, args ):
        self.need_cleanup = content.aq_parent.implements('isPortalRoot')
        self.root_item = content.getUid()
        self.root_url = content.absolute_url(1)

        self.get_items = ItemsWalker( content, args )
        self.info_dict = self.get_items.info

class Jungle:
    """
        Renders DTML tag "jungle" which represent object tree widget based ond on
        catalog tool.

        Syntax:

          jungle tag syntax::

            <dtml-jungle [VariableName|expr="VariableExpression"]>
            </dtml-jungle>

          The jungle tag is a block tag. It renders a dynamic tree widget in
          HTML. The root of the tree is given by variable name or expression,
          if present, otherwise it defaults to the current object. The tree
          block is rendered for each tree node, with the mybrains instance of
          node pushed onto the DTML namespace.

          Tag have three modes of rendering:

            1. **Static** (default).
               Similar to standard tree tag - page reload after the node is
               opened or closed.
            2. **Pseudo dynamic**.
               All tree contents loading into single page and closing/opening
               via javascripts without page reloading.
            3. **Dynamic**.
               As in static mode only open branches contents loading into page.
               But page reloading doesn't happen because contents of closed
               branches downloading when it needed with use of HTTP requests
               generated by javascript. This mode working only for IE (from
               late versions of 5.0) and Mozilla (from 0.9.7).

          Javascripts used in dynamic modes contained into *skins/common/jungle_dynamic_js.dtml*.

          Tree state is set in HTTP cookies. Thus for trees to remember their
          state after you leave the page, cookies must be enabled.

        Attributes:

          'state_id' -- The string prefix of the HTTP cookies and the session
                        information. Used to differ multiple trees on single
                        page.

          'state_url' -- The URL of the HTTP cookies. Used to differ multiple
                         trees on single page.

          'sort_order' -- String with comma-separated list of catalog indexes
                          names describing the sorting order.

          'single' -- Boolean value. Allows only one branch to be expanded at
                      a time. When you expand a new branch, any other expanded
                      branches close. Implemented only for *static* mode.

          'urlparams' -- A query string which is included in the expanding and
                         contracting widget links. This attribute is for advanced
                         usage only. Implemented only for *static* mode.

          'prefix' -- Provide versions of the tag variables that start with this
                      string prefix instead of "tree", and that use
                      underscores (_) instead of hyphens (-). The prefix must
                      start with a letter and contain only alphanumeric
                      characters and underscores (_).

          'meta_types' -- String with comma-separated list of meta_types of
                          objects that will be shown on the tree.

          'implements' -- String with comma-separated list list of implements
                          keywords of objects that will be shown on the tree.

          'dynamic' -- This expression evaluates boolean value that turns
                       *dynamic* mode on or off.

          'pseudo_dynamic' -- This expression evaluates boolean value that turns
                              *pseudo dynamic* mode on or off.

          'dynamic_item_id' -- string identifier of the item that will present
                               open branches contents in *dynamic* mode.

          'dynamic_item' -- Set this tag to render open branches content in
                            *dynamic* mode.

        Tag Variables:

          'tree-item-expanded' -- True if the current node is expanded.

          'tree-item-url' -- The URL of the current node.

          'tree-root-url' -- The URL of the root node.

          'tree-root-id' -- The identifier of the root node.

          'tree-level' -- The depth of the current node. Top-level nodes have
                          a depth of zero.

        Tag Control Variables:

          You can control the tree tag by setting this variable.

          'collapse_all' -- If this variable is true then the entire tree is
                            collapsed.
    """
    name = 'jungle'
    blockContinuations = ()
    expand = None

    _registered_trees = {}

    _defaultTreeFactory = ContentTree

    def __init__(self, blocks):
        tname, args, section = blocks[0]
        args = parse_params(args, dynamic_item=1,
                          name=None, expr=None, tree=None,
                          # expand=None, leaves=None, header=None, footer=None, reverse=1, *TODO*
                          sort_order=None,
                          # id=None, url=None, *TODO*(?)
                          single=1,
                          # nowrap=1, content_filter=None,
                          # assume_children=1, *TODO*(?)
                          urlparams=None,
                          prefix=None,
                          state_id=None, state_url=None, # used to differ multiple trees on page
                          meta_types=None, implements=None,
                          dynamic=1,
                          dynamic_item_id=None,
                          pseudo_dynamic=1
                          # opened_decoration=None, *TODO*
                          # closed_decoration=None, *TODO*
                          # childless_decoration=None, *TODO*
                          # endofbranch_decoration=None, *TODO*
                          # pl_icon=None, *TODO*
                          # mi_icon=None, *TODO*
                          )
        has_key = args.has_key

        if has_key('') or has_key('name') or has_key('expr'):
            name, expr = name_param(args,'tree',1)

            if expr is not None:
                args['expr'] = expr
            elif has_key(''):
                args['name'] = name
        else:
            name = 'a tree tag'

        if has_key('meta_types'):
            args['meta_types'] = [meta_type.strip() for meta_type in args['meta_types'].split(',')]

        if has_key('implements'):
            args['implements'] = [feature.strip() for feature in args['implements'].split(',')]

        if has_key('sort_order'):
            args['sort_order'] = args['sort_order'].split(',')

        if has_key('dynamic'):
            if has_key('pseudo_dynamic'):
                raise ParseError, _tm('dynamic and pseudo_dynamic given', 'tree')

            if type(args['dynamic']) is StringType:
                args['dynamic'] = Eval(args['dynamic']).eval

            if not args.get('dynamic_item_id'):
                args['dynamic_item_id'] = 'dynamic_tree_item'

        elif has_key('pseudo_dynamic') and type(args['pseudo_dynamic']) is StringType:
            args['pseudo_dynamic'] = Eval(args['pseudo_dynamic']).eval

        if has_key('urlparams'):
            args['urlparams'] = Eval(args['urlparams']).eval
        else:
            args['urlparams'] = {}

##        if not has_key('childless_decoration'):
##            args['childless_decoration']=''

        prefix = args.get('prefix')
        if prefix and not simple_name(prefix):
            raise ParseError, _tm(
                'prefix is not a simple name', 'tree')

        if not has_key('state_id'):
            args['state_id'] = 'jungle'

        if not has_key('state_url'):
            args['state_url'] = '/'

        self.__name__ = name
        self.section = section.blocks
        self.args = args

    def render(self,md):
        """
            DocumentTemplate render
        """
        args = self.args.copy()
        have = args.has_key

        if have('dynamic_item'):
            # Dynamic item receiving args through session
            args_from_session = md['REQUEST'].SESSION.get(args['state_id']+'_args', None)
            if args_from_session is not None:
                args.update( dict(args_from_session) )
                mode = 'dynamic'
            else:
                # When session args are lost return internal server error response
                md['REQUEST'].RESPONSE.setStatus(500)
                return "<!-- SESSION ARGS LOST -->"
        else:
            if have('urlparams') and callable(args['urlparams']):
                args['urlparams'] = args['urlparams'](md)


            mode = 'static'
            for _mode in ('pseudo_dynamic', 'dynamic',):
                if have(_mode):
                    if callable(args[_mode]):
                        mode_set = args[_mode](md)
                    else:
                        mode_set = args[_mode]
                    if mode_set:
                        mode = _mode
                    break

        args['mode'] = mode

        if have('name'):
            tree = md[ args['name'] ]
        elif have('expr'):
            tree = args['expr'].eval(md)
        else:
            tree = md.this

        if not getObjectImplements( tree, IBasicTree ):
            tree = self._defaultTreeFactory( tree, args )

        return tpRenderItem(tree, md, self.section, args)

    __call__ = render

def walkTree(item, get_items, args, skip=False, expand_all=False):
    """
        return tree with scope of item

        Arguments:
            item - item from which contruct tree
            get_items - a function with one argument item that returns the subitems of item

            args - jungle args

            skip - if true, ignored sub_item subTree

            expand_all - if true, all Tree expanded
    """
    #LOG( 'walkTree', INFO, locals() )
    ret = {}
    mode = args['mode']
    state = args['state']

    assert callable(get_items), repr(get_items)
    for sub_item in get_items(item):

        state.empty( sub_item )

        if state.isEmpty(item):
            (skip and state.close or state.open)( item )

        if not skip or mode == 'pseudo_dynamic':
            ret[sub_item] = walkTree( sub_item
                                    , get_items
                                    , args
                                    , skip=not (expand_all or state.isOpened(sub_item) )
                                    , expand_all=expand_all
                                    )
    return ret

class ItemsWalker( object ):
    def __init__(self, object, args ):
        """
           'info' is a dict nd_uid -> path
        """
        self.root_item = object.getUid()

        self.catalog = getCatalogByType( object, ResourceUid( object ) )

        self.uid2path = {}
        self.info = {}
        self.args = args

        self.insert( self.root_item )

    def getCatalog(self):
        return self.catalog

    def __call__(self, item):
        """
        """
        is_root = not self.args.has_key('dynamic_item') and item == self.root_item

        path = self.uid2path[item]

        query = {}

        if is_root:
            query['path'] = path

            # sort results is very needed by bindChildren2Root
            query['sort_on'] = 'path'

            query['nd_uid'] = {'query':self.root_item, 'operator':'not'}
        else:
            query['parent_path'] = path

        args = self.args
        if args.has_key('meta_types'):
            query['meta_type'] = args['meta_types']

        if args.has_key('implements'):
            query['implements'] = args['implements']

        results = self.getCatalog().searchResults( **query )

        if is_root:
            results = self.bindChildren2Root(results)

        for item in results:
            uid = item['nd_uid']
            self.insert(uid, item)
            yield uid

    def insert(self, item, brains=Missing):
        if brains is Missing:
            brains = self.getCatalog().getMetadataByUid( item )

        self.uid2path[item] = brains.getPath()
        self.info[item] = brains

    def bindChildren2Root(self, results):
        prev = None
        for r in results:
            uid = r['nd_uid']
            path = r.getPath()
            
            if prev and path.startswith( prev + pathdelim ):
                continue
            else:
                prev = path
                yield r

def tpRenderItem(tree, md, section, args):
    """
        Render data organized as a tree

        Arguments:

            'root_item' - root item

            'root_url' root url needed for new style

            'info_dict' - dict {(item1, info1).....}

            'get_items' - a function with one argument item that returns the subitems of item

            'md' - TempaleteDict instance

            'section' - sections to render

            'args' - jungle args

    """
    # XXX
    root_item, info_dict, get_items, need_cleanup = tree.root_item, tree.info_dict, tree.get_items, tree.need_cleanup
    mode = args['mode']

    # extra data to dtmls
    treeData = add_with_prefix( {}, 'tree', args.get('prefix'))
    treeData['tree-root-item'] = root_item
    treeData['tree-root-url'] = tree.root_url

    if args.has_key('dynamic_item'):
        treeData['tree-dynamic-item'] = True

    # Decoding state list
    state = TreeState( args['state_id'], args['state_url'] )
    state.open( root_item )

    if md.has_key('collapse_all'):
        pass
    elif md.has_key('expand_all'):
        pass  # *TODO*
    else:
        state.loadState( md )

    #print 'loaded state ->', `state.state`
    args['state'] = state

    # Building items_tree
    item_tree = walkTree(root_item, get_items, args, expand_all=md.has_key('expand_all'))

    ret = BasicOutput()
    # Applying script tag for dynamic and pseudo_dynamic modes
    if mode != 'static' and not args.has_key('dynamic_item'):
        ret += '<script language="javascript" src="%s/jungle_dynamic_js"></script>\n' %md['portal_url']
        if mode == 'dynamic':
            # Passing if needed some args to subbranches using session
            session = md['REQUEST'].SESSION
            session_args = [ (k,v) for (k,v) in args.items() if k in _transmitted_args ]
            session_key = args['state_id']+'_args'
            if session.get(session_key) != session_args:
                session[session_key] = session_args

    md._push( treeData )
    md._push( InstanceDict( info_dict[root_item], md ) )
    try:
        tpRenderTABLE( root_item
                     , item_tree
                     , info_dict
                     , section
                     , md
                     , ret 
                     , treeData
                     , level=0
                     , args=args)
    finally:
        md._pop(2)

    if not args.get('single'):
        state.saveState( md, info_dict.keys(), need_cleanup)

    return ret.getvalue()

def tpRenderTABLE(item, item_tree, info_dict, section, md, output, treeData, level=0, args=None):
    """
    Render a tree as a table
        Arguments:

            'item' - item to render

            'item_tree' - Tree of items

            'info_dict' - dict {(item1, info1).....}

            'md' - TempaleteDict instance

            'level' - level of the item in the Tree

            'section' - sections to render

            'args' - jungle args

    """
    ret = output
    item_info = info_dict[item]

    self_url = md['URL']
    try: self_url = splitpath( self_url )[1]
    except IndexError: pass

    have_arg=args.has_key
    mode = args['mode']
    state = args['state']

    portal_url = md.getitem('portal_url',0)(1)
    not_empty = not state.isEmpty(item)
    expanded = state.isOpened(item)

    treeData['tree-item-expanded'] = expanded
    treeData['tree-item'] = item
    treeData['tree-level'] = level
    treeData['tree-colspan'] = 0

    root_url = treeData['tree-root-url']

    table_head = '''<table cellpadding="0" cellspacing="0" border="0" width="100%%">
                 <tr><td colspan="2" style="%s">'''

    if mode != 'static' and not_empty and level:
        treeData['tree-item-expanded'] = False

        ret += '''<div style="display:%s;">
                    %s
                    %s</td></tr></table>
                  </div>''' % ( expanded and 'none' or 'block'
                              , table_head % ''
                              , render_blocks(section, md)
                              )

        if mode == 'pseudo_dynamic' or expanded:
            ret += '<div style="display:%s;">' % (mode == 'dynamic' and 'block' or 'none')

        treeData['tree-item-expanded'] = True

    if not (mode == 'dynamic' and state.isClosed(item)):
        # In dynamic mode we don't need following stuff if branch is closed
        ret += table_head \
               % (treeData['tree-item-expanded'] and ' background: url('+portal_url+'/thread_I_bg.gif) no-repeat;' or '')

        ret += render_blocks(section, md) + '</td></tr>\n'

        sub_items = item_tree.keys()

        if len(sub_items) > 1:
            if have_arg('sort_order'):

                sort = [ (order_key,'cmp',have_arg('reverse') and 'desc' or 'asc')
                         for order_key in args['sort_order'] ]

                sub_items = [ res[0] for res in
                             SortEx( [ (sub_item, info_dict[sub_item]) for sub_item in sub_items]
                                   , sort)]

        for sub_item in sub_items:
            # Working on subitems of current item
            branch_end = sub_items[-1] == sub_item

            sub_item_info = info_dict[sub_item]

            img_tag = '<%s src="%s/thread_%s%s.gif"'\
                      % ((not state.isEmpty(sub_item) and (mode != 'static')) and 'input type=image' or 'img',
                         portal_url, (branch_end and 'L' or 'T'), state.getImgPostfix( sub_item ) )

            if not state.isEmpty(sub_item):

                diff = [sub_item]
                s = encode_seq(diff)

                # Propagate extra args through tree.
                params = args.get('urlparams',{})

                if mode != 'dynamic':

                    if mode == 'pseudo_dynamic':
                        img_tag += ''' onClick="nodeAction(this, '%s', '%s');">'''\
                                    % (args['state_url'], s)
                    else:
                        img_tag += '>'

                        params['disable_dynamic:int'] = 1

                        if state.isOpened(sub_item):
                            params['tree-c'] = s
                        else:
                            params['tree-e'] = s

                        self_url_with_params = addQueryString( self_url, params)
                        img_tag = '<a href="%s">%s</a>' % (self_url_with_params, img_tag)

                else:
                    params['dynamic_item'] = sub_item
                    sub_url_with_params = addQueryString( '%s/%s'\
                                                          %(root_url, args['dynamic_item_id'])
                                                        , params)
                    img_tag += ''' onClick="nodeAction( this, '%s', '%s', '%s');">'''\
                                % (args['state_url'], s, sub_url_with_params)
            else:
                img_tag += '>'

            ret += '''<tr>
                   <td%s width="16" valign="top">%s</td>
                   <td width="100%%">''' %(( not branch_end and ' background="'+portal_url+'/thread_I.gif"' or ''), img_tag)

            md._push( InstanceDict( sub_item_info, md ) )
            try:
                tpRenderTABLE( sub_item
                             , item_tree[sub_item]
                             , info_dict
                             , section
                             , md
                             , ret
                             , treeData
                             , level+1
                             , args )


            finally:
                md._pop()

            ret += '</td></tr>'

        ret += '</table>\n'

    if level and not_empty and (mode == 'pseudo_dynamic' or (mode == 'dynamic' and expanded)):
        ret += '</div>'

class TreeState( object ):

    OPENED = 1
    EMPTY = 0
    CLOSED = -1

    # used to translate item_state to img tag src
    _img_postfix = {CLOSED:'_closed', EMPTY:'', OPENED:'_opened'}

    def __init__(self, id, url):
        self.id = id
        self.url = url

        # following parameters used in isOpened, walkTree, apply_diff, tpRenderTABLE
        # dictionary that represents item state by url (-1 - closed, 1 - opened, 0 - empty)
        self.item_state_dict = {}

        # set that represents open items set in following format:
        # Set(item, item2)
        # this means that item1, item2 items opened
        self.state = Set() 
  
    def decodeState(self, state):
        """
            Convert an encoded string to a dict

            Arguments:
                s - encoded string
        """
        return decode_seq(state)

    def encodeState(self, cleanup=False, info=Missing):
        """
            Convert a state dict to an encoded string

            Arguments:
                cleanup - if true, state filtered to
                                remove item ids of deleted items

                info - list of item ids

            Result : encoded string
        """
        info = info or []
        state = self.state
        if cleanup:
            state = filter( lambda item, info=info: item in info, state )
        else:
            state = list(state)

        return encode_seq(state)

    def loadState(self, md):
        if md.has_key('tree-s' + self.id):
            try:
                state = self.decodeState(md['tree-s' + self.id])
            except:
                LOG( 'renderTree.tree-state', INFO, 'Bad state [%s]' % state )
            else:
                for item in state:
                    self.open(item)

        if md.has_key('tree-e'):
            try:
                diff = decode_seq(md['tree-e'])
            except:
                LOG( 'renderTree.tree-expand', INFO, 'Bad diff [%s]' % md['tree-e'] )
            else:
                # open
                for item in diff:
                    self.open(item)
        if md.has_key('tree-c'):
            try:
                encoded_diff = md['tree-c']
                if encoded_diff.count('%2C'):
                    parts = encoded_diff.split('%2C')
                    diff = map( lambda part: decode_seq(part)[0], parts )
                else:
                    diff = decode_seq(encoded_diff)
            except:
                LOG( 'renderTree.tree-collapse', INFO, 'Bad diff [%s]' % md['tree-c'] )
            else:
                # close
                for item in diff:
                    self.close(item)

    def saveState(self, md, info_list, need_cleanup):
        """ encode new state and set it to cookie """
        state = self.encodeState(cleanup=need_cleanup, info=info_list)
        md['RESPONSE'].setCookie('tree-s' + self.id, state, path=self.url)

    def isOpened(self, item):
        """
            Checks that url branch is opened

            Arguments:
                item - item to check on

                self - Tree state

            Result:
                boolean value

        """
        return item in self.state

    def isClosed(self, item ):
        return self.item_state_dict.get(item) == self.CLOSED

    def isEmpty(self, item ):
        return self.item_state_dict.get(item) == self.EMPTY
 
    def getImgPostfix(self, item):
        return self._img_postfix[ self.item_state_dict[item] ]

    def open(self, item):
        self.item_state_dict[item] = self.OPENED
        self.state.add(item)

    def close(self, item):
        self.item_state_dict[item] = self.CLOSED
        self.state.discard(item)

    def empty(self, item):
        self.item_state_dict[item] = self.EMPTY

class BasicOutput( object ):

    def __init__(self):
        self.data = []

    def write(self, part ):
        # TODO: str( part )
        self.data.append(part)

    def __add__(self, data):
        self.write( data )

        # XXX: use write everywhere
        return self
   
    def getvalue(self):
        return ''.join( self.data )

def registerStaticJungleTree( id, tree):
    assert getObjectImplements( tree, IBasicTree ), repr(tree)

    Jungle._registered_trees[id] = tree

def initialize( context ):
    context.register( registerStaticJungleTree )
  
    context.registerDTCommand( Jungle.name, Jungle )
