#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../ops/lib/runtime_env.sh
source "${ROOT_DIR}/ops/lib/runtime_env.sh"
docflow_load_env "${ROOT_DIR}"
docflow_export_runtime

docker exec \
  -e DOCFLOW_ADMIN_USERNAME="${DOCFLOW_ADMIN_USERNAME}" \
  -e DOCFLOW_ADMIN_PASSWORD="${DOCFLOW_ADMIN_PASSWORD}" \
  -e DOCFLOW_ROLE_DEFAULT_PASSWORD="${DOCFLOW_ROLE_DEFAULT_PASSWORD}" \
  -e DOCFLOW_MANAGER_USERNAME="${DOCFLOW_MANAGER_USERNAME}" \
  -e DOCFLOW_EMPLOYEE_USERNAME="${DOCFLOW_EMPLOYEE_USERNAME}" \
  -e DOCFLOW_REQUESTER_USERNAME="${DOCFLOW_REQUESTER_USERNAME}" \
  -e DOCFLOW_OFFICE_USERNAME="${DOCFLOW_OFFICE_USERNAME}" \
  -e DOCFLOW_NURSE_USERNAME="${DOCFLOW_NURSE_USERNAME}" \
  -e BRIDGE_BASE_URL="${BRIDGE_BASE_URL}" \
  -e DOCFLOW_PUBLIC_BASE="${DOCFLOW_PUBLIC_BASE}" \
  -e RUKOVODITEL_PUBLIC_URL="${RUKOVODITEL_PUBLIC_URL}" \
  "${RUKOVODITEL_CONTAINER_NAME}" php /var/www/html/scripts/provision_test_users.php "$@"
