#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/runtime_env.sh
source "${SCRIPT_DIR}/lib/runtime_env.sh"

ROOT_DIR="$(docflow_default_root "${SCRIPT_DIR}")"

ENV_MODE="${DOCFLOW_ENV_MODE:-production}"
DOMAIN="${DOCFLOW_DOMAIN:-docflow.hospital.local}"
PROJECT_ROOT_VALUE="${DOCFLOW_PROJECT_ROOT:-/opt/docflow}"
NAME_PREFIX="${DOCFLOW_NAME_PREFIX:-docflow}"
IMAGE_PREFIX="${DOCFLOW_IMAGE_PREFIX:-docflow}"
HTTP_BIND_PORT="${DOCFLOW_HTTP_BIND_PORT:-80}"
HTTPS_BIND_PORT="${DOCFLOW_HTTPS_BIND_PORT:-443}"
RUKOVODITEL_BIND_PORT="${DOCFLOW_RUKOVODITEL_BIND_PORT:-18081}"
BRIDGE_BIND_PORT="${DOCFLOW_BRIDGE_BIND_PORT:-18082}"
NAUDOC_BIND_PORT="${DOCFLOW_NAUDOC_BIND_PORT:-18080}"
ONLYOFFICE_BIND_PORT="${DOCFLOW_ONLYOFFICE_BIND_PORT:-18083}"
OFFICE_DEPLOYMENT_MODE="${DOCFLOW_OFFICE_DEPLOYMENT_MODE:-shell_only}"
DOCSPACE_INTERNAL_PORT="${DOCFLOW_DOCSPACE_INTERNAL_PORT:-19001}"
WORKSPACE_INTERNAL_PORT="${DOCFLOW_WORKSPACE_INTERNAL_PORT:-19002}"
OUTPUT_FILE="${1:-${ROOT_DIR}/.env.generated.hospital}"

if [ -f "${OUTPUT_FILE}" ]; then
  echo "[env] refusing to overwrite existing file: ${OUTPUT_FILE}" >&2
  echo "[env] remove it first or pass a different output path" >&2
  exit 1
fi

DB_PASSWORD="$(docflow_random_secret 24)"
DB_ROOT_PASSWORD="$(docflow_random_secret 24)"
NAUDOC_PASSWORD="$(docflow_random_secret 24)"
BRIDGE_SYNC_CONTROL_TOKEN="$(docflow_random_secret 32)"
ONLYOFFICE_JWT_SECRET="$(docflow_random_secret 32)"
LDAP_ADMIN_PASSWORD="$(docflow_random_secret 24)"
LDAP_CONFIG_PASSWORD="$(docflow_random_secret 24)"
LDAP_BIND_PASSWORD="$(docflow_random_secret 24)"
DOCFLOW_ADMIN_PASSWORD="$(docflow_random_secret 24)"
DOCFLOW_ROLE_DEFAULT_PASSWORD="$(docflow_random_secret 24)"

HTTPS_SUFFIX=""
HTTPS_SUFFIX_ESCAPED=""
if [ "${HTTPS_BIND_PORT}" != "443" ]; then
  HTTPS_SUFFIX=":${HTTPS_BIND_PORT}"
  HTTPS_SUFFIX_ESCAPED="%3A${HTTPS_BIND_PORT}"
fi

HTTP_SUFFIX=""
if [ "${HTTP_BIND_PORT}" != "80" ]; then
  HTTP_SUFFIX=":${HTTP_BIND_PORT}"
fi

DOCSPACE_TARGET_URL=""
WORKSPACE_TARGET_URL=""
REQUIRE_LIVE_TARGETS="0"

case "${OFFICE_DEPLOYMENT_MODE}" in
  shell_only)
    ;;
  same_host_proxy)
    DOCSPACE_TARGET_URL="http://host.docker.internal:${DOCSPACE_INTERNAL_PORT}/"
    WORKSPACE_TARGET_URL="http://host.docker.internal:${WORKSPACE_INTERNAL_PORT}/"
    REQUIRE_LIVE_TARGETS="1"
    ;;
  *)
    echo "[env] unsupported DOCFLOW_OFFICE_DEPLOYMENT_MODE: ${OFFICE_DEPLOYMENT_MODE}" >&2
    echo "[env] supported values: shell_only, same_host_proxy" >&2
    exit 1
    ;;
esac

cat > "${OUTPUT_FILE}" <<EOF
# Generated on $(date -Iseconds)
# Hospital-oriented ${ENV_MODE} baseline.
# Review all values before renaming this file to .env on the target server.

PROJECT_ROOT=${PROJECT_ROOT_VALUE}

# Public URLs
DOCFLOW_ACCESS_HOST=
DOCFLOW_ACCESS_HOST_AUTO=1
DOCFLOW_ACCESS_REPORT_PATH=runtime/monitoring/access_points.txt
GATEWAY_SERVER_NAME=${DOMAIN}
GATEWAY_EXTERNAL_HTTPS_PORT=${HTTPS_BIND_PORT}
GATEWAY_EXTERNAL_HTTP_SUFFIX=${HTTP_SUFFIX}
GATEWAY_EXTERNAL_HTTPS_SUFFIX=${HTTPS_SUFFIX}
GATEWAY_EXTERNAL_HTTPS_SUFFIX_ESCAPED=${HTTPS_SUFFIX_ESCAPED}
GATEWAY_TLS_CN=${DOMAIN}
GATEWAY_BIND_HTTP_PORT=${HTTP_BIND_PORT}
GATEWAY_BIND_HTTPS_PORT=${HTTPS_BIND_PORT}
RUKOVODITEL_BIND_PORT=${RUKOVODITEL_BIND_PORT}
BRIDGE_BIND_PORT=${BRIDGE_BIND_PORT}
NAUDOC_BIND_PORT=${NAUDOC_BIND_PORT}
ONLYOFFICE_BIND_PORT=${ONLYOFFICE_BIND_PORT}
RUKOVODITEL_PUBLIC_URL=https://${DOMAIN}${HTTPS_SUFFIX}
NAUDOC_PUBLIC_URL=https://${DOMAIN}${HTTPS_SUFFIX}/docs
DOCSPACE_PUBLIC_URL=https://${DOMAIN}${HTTPS_SUFFIX}/docspace
WORKSPACE_PUBLIC_URL=https://${DOMAIN}${HTTPS_SUFFIX}/workspace
ONLYOFFICE_PUBLIC_JS_API_URL=https://${DOMAIN}${HTTPS_SUFFIX}/office/web-apps/apps/api/documents/api.js
DOCSPACE_ENABLED=1
WORKSPACE_ENABLED=1
DOCSPACE_TARGET_URL=${DOCSPACE_TARGET_URL}
DOCSPACE_COLLABORATION_ROOM_TARGET_URL=
DOCSPACE_PUBLIC_ROOM_TARGET_URL=
DOCSPACE_FORM_FILLING_ROOM_TARGET_URL=
WORKSPACE_TARGET_URL=${WORKSPACE_TARGET_URL}
WORKSPACE_CALENDAR_TARGET_URL=
WORKSPACE_COMMUNITY_TARGET_URL=
DOCFLOW_OFFICE_WAVE1_REQUIRE_LIVE_TARGETS=${REQUIRE_LIVE_TARGETS}
DOCFLOW_WORKSPACE_WAVE1_ENABLE_COMMUNITY=0

# Internal URLs
BRIDGE_BASE_URL=http://host.docker.internal:${BRIDGE_BIND_PORT}
RUKOVODITEL_BASE_URL=http://host.docker.internal:${RUKOVODITEL_BIND_PORT}
NAUDOC_BASE_URL=http://host.docker.internal:${NAUDOC_BIND_PORT}/docs
SYNC_CONTROL_URL=http://host.docker.internal:${RUKOVODITEL_BIND_PORT}/run_sync_job.php
ONLYOFFICE_INTEGRATION_BASE_URL=http://rukovoditel

# Gateway upstreams
GATEWAY_RUKOVODITEL_UPSTREAM=host.docker.internal:${RUKOVODITEL_BIND_PORT}
GATEWAY_BRIDGE_UPSTREAM=host.docker.internal:${BRIDGE_BIND_PORT}
GATEWAY_NAUDOC_UPSTREAM=host.docker.internal:${NAUDOC_BIND_PORT}
GATEWAY_NAUDOC_UPSTREAM_ESCAPED=host.docker.internal%3A${NAUDOC_BIND_PORT}
GATEWAY_ONLYOFFICE_UPSTREAM=host.docker.internal:${ONLYOFFICE_BIND_PORT}

# Image tags for portable/offline deployment
GATEWAY_IMAGE=${IMAGE_PREFIX}/gateway:local
BRIDGE_IMAGE=${IMAGE_PREFIX}/bridge:local
RUKOVODITEL_APP_IMAGE=${IMAGE_PREFIX}/rukovoditel-app:local
NAUDOC_LEGACY_IMAGE=${IMAGE_PREFIX}/naudoc-legacy:local
MARIADB_IMAGE=mariadb:10.11
ONLYOFFICE_IMAGE=onlyoffice/documentserver:latest
LDAP_IMAGE=osixia/openldap:1.5.0

# Runtime
SYNC_INTERVAL_SECONDS=180
BRIDGE_REQUEST_TIMEOUT=8
BRIDGE_GUNICORN_WORKERS=1
BRIDGE_GUNICORN_THREADS=2
BRIDGE_GUNICORN_TIMEOUT=60
BRIDGE_DB_PATH=/data/bridge.db

# Databases and secrets
RUKOVODITEL_DB_NAME=rukovoditel
RUKOVODITEL_DB_USER=rukovoditel
RUKOVODITEL_DB_PASSWORD=${DB_PASSWORD}
RUKOVODITEL_DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
NAUDOC_USERNAME=admin
NAUDOC_PASSWORD=${NAUDOC_PASSWORD}
BRIDGE_SYNC_CONTROL_TOKEN=${BRIDGE_SYNC_CONTROL_TOKEN}
ONLYOFFICE_JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
LDAP_DOMAIN=hospital.local
LDAP_ORGANISATION=Hospital_DocFlow
LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
LDAP_CONTAINER_NAME=${NAME_PREFIX}_hospital_ldap
DOCFLOW_ADMIN_USERNAME=admin
DOCFLOW_ADMIN_PASSWORD=${DOCFLOW_ADMIN_PASSWORD}
DOCFLOW_ROLE_DEFAULT_PASSWORD=${DOCFLOW_ROLE_DEFAULT_PASSWORD}
DOCFLOW_OFFICE_ADMIN_EMAIL=admin@hospital.local
DOCFLOW_OFFICE_ADMIN_PASSWORD=Admin2026!
DOCFLOW_SHOW_DEMO_LOGIN_MODES=0
DOCFLOW_MANAGER_USERNAME=department.head
DOCFLOW_EMPLOYEE_USERNAME=clinician.primary
DOCFLOW_REQUESTER_USERNAME=registry.operator
DOCFLOW_OFFICE_USERNAME=records.office
DOCFLOW_NURSE_USERNAME=nurse.coordinator

# Container names for production-like deployment
GATEWAY_CONTAINER_NAME=${NAME_PREFIX}_gateway
GATEWAY_COMPOSE_PROJECT_NAME=${NAME_PREFIX}_gateway
BRIDGE_CONTAINER=${NAME_PREFIX}_bridge
RUKOVODITEL_CONTAINER_NAME=${NAME_PREFIX}_rukovoditel
RUKOVODITEL_DB_CONTAINER=${NAME_PREFIX}_rukovoditel_db
ONLYOFFICE_CONTAINER_NAME=${NAME_PREFIX}_onlyoffice_docs
RUKOVODITEL_SYNC_WORKER_CONTAINER_NAME=${NAME_PREFIX}_sync_worker
NAUDOC_LEGACY_CONTAINER=${NAME_PREFIX}_naudoc_legacy
MIDDLEWARE_COMPOSE_PROJECT_NAME=${NAME_PREFIX}_middleware
RUKOVODITEL_COMPOSE_PROJECT_NAME=${NAME_PREFIX}_rukovoditel
NAUDOC_LEGACY_COMPOSE_PROJECT=${NAME_PREFIX}_legacy
NAUDOC_LEGACY_SERVICE=naudoc_legacy
EOF

chmod 600 "${OUTPUT_FILE}" 2>/dev/null || true

echo "[env] generated: ${OUTPUT_FILE}"
echo "[env] domain: ${DOMAIN}"
echo "[env] mode: ${ENV_MODE}"
echo "[env] next step: review values and rename/copy to ${ROOT_DIR}/.env on the target server"
